apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-placeholder
    tier: jss
  name: jss-client-placeholder
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: client-placeholder
      tier: jss
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-placeholder
        app-group: group-placeholder
        tier: jss
    spec:
      containers:
      - env:
        - name: JSS_NAME
          value: client-placeholder
        - name: JSS_DB_NAME
          value: client-placeholder
        - name: JSS_DB_USERNAME
          value: client-placeholder
        - name: JSS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: client-placeholder-mysql-jss-user.txt
              name: client-placeholder-mysql-jss-user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: client-placeholder-mysql-root.txt
              name: client-placeholder-mysql-root
        image: registry.datajar.mobi:5000/jss-client-placeholder:jss-version-placeholder
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthCheck.html
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 600
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: jss-client-placeholder
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: datajar-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
