apiVersion: v1
kind: Service
metadata:
  name: mysql-client-placeholder
  labels:
    app: client-placeholder
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: client-placeholder
    tier: mysql
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-client-placeholder
  labels:
     app: client-placeholder
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: client-placeholder
        tier: mysql
    spec:
      containers:
      - image: registry.datajar.mobi:5000/mysql-client-placeholder:mysql-version-placeholder
        name: mysql-client-placeholder
        command: ["/bin/sh", "/usr/local/bin/run.sh"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: client-placeholder-mysql-root
              key: client-placeholder-mysql-root.txt
        - name: MYSQL_DATABASE
          value: client-placeholder
        - name: MYSQL_USER
          value: client-placeholder
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: client-placeholder-mysql-jss-user
              key: client-placeholder-mysql-jss-user.txt
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: client-placeholder-mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: client-placeholder-mysql
        persistentVolumeClaim:
          claimName: client-placeholder-mysql
      imagePullSecrets:
      - name: datajar-registry