apiVersion: v1
kind: PersistentVolume
metadata:
  name: client-placeholder-mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.16.106.11
    path: "/data/client-placeholder-mysql"
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: client-placeholder-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
